USE [master]
GO

/****** Object:  Database [CDN]    Script Date: 21/9/2023 10:22:18 PM ******/
CREATE DATABASE [CDN]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CDN', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CDN.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CDN_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CDN_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CDN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CDN] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CDN] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CDN] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CDN] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CDN] SET ARITHABORT OFF 
GO

ALTER DATABASE [CDN] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CDN] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CDN] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CDN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CDN] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CDN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CDN] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CDN] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CDN] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CDN] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CDN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CDN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CDN] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CDN] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CDN] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CDN] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CDN] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CDN] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CDN] SET  MULTI_USER 
GO

ALTER DATABASE [CDN] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CDN] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CDN] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CDN] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CDN] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CDN] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CDN] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CDN] SET  READ_WRITE 
GO


